services:
  - type: web
    name: smart-healthcare-poc
    env: python
    region: ohio
    buildCommand: "cd smart-healthcare-poc/backend && pip install -r requirements.txt"
    startCommand: "cd smart-healthcare-poc/backend && gunicorn app:app"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
